### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by filipedeoliveira** [cesium/sei16-website#6]
O bug que encontrei foi na secção partners, no logo da comissão de festas de MIEI que redirecciona para o site da subvisual.

**Comment by frmendes** [comment]
Thanks!

I'll handle this in a bit. In the meantime, what's your SEI username, so I can give you the `Bug Catcher` badge?

**Comment by filipedeoliveira** [comment]
filipeoliveira
Em 11/02/2016 11:53, "Fernando Mendes" <notifications@github.com> escreveu:

**Comment by frmendes** [comment]
Just added the badge. Everything should be set up!

@martinhoaragao once you deploy it, this should close. See #7.
