### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DiogoAFD** [cesium/sei16-website#8]
Acho que encontrei um bug na plataforma, escolhi uma badge para ver quem eram os participantes que tinham a badge e acho que a lista tem um "furo".

**Comment by frmendes** [comment]
@DiogoAFD screen me, please.

**Comment by DiogoAFD** [comment]
![12736272_1261479390547519_1344426383_n](https://cloud.githubusercontent.com/assets/15615965/12980108/dd2955f0-d0d2-11e5-932f-5ec5eceb2d84.jpg)

**Comment by frmendes** [comment]
Oh, ok. This is an issue for the [internal webapp](https://github.com/cesium/intra.seium.org).

I have to check if it's really an issue because this was well documented last year, we were just too lazy to fix it. I'll check with the rest of the organisers if I can give you the badge.

**Comment by frmendes** [comment]
I just gifted you the badge.
